Feature/75 signal assignees
Amsterdam/signals-frontend pull request #1160
Opened 2020-10-01 12:53 UTC by boris-arkenaar

Assign an incident to an employee

according to Signalen/frontend#75

## Functionally

The functionality described below has been put under the feature flag `assignSignalToEmployee` which is turned off by default.

- An extra column in the incident management overview table where the username of the employee will be shown in case the incident has been assigned, otherwise empty.
- An extra field on the right side of the incident management detail page displaying the username of the employee in case the incident has been assigned, otherwise indicating the incident has not been assigned to an employee.
- Editability of the aforementioned field showing a list of users.

## Other changes

### Fetching users

Users are now fetched in the [incident management module](src/signals/incident-management/index.js) and put into the `IncidentManagementContext`.

### Change value

For the `ChangeValue` component the key of an item in the list of possible values, can have an explicit falsy value. This will be [handled as an empty string](src/signals/incident-management/components/SelectInput/index.js) `''` in the front facing logic, but the [original explicit falsy value will be used](ChangeValue) (e.g. `null`, `0`, `''`) in the logic going towards the backend.

In this case the incident endpoint is expecting a `null` value for `assigned_user_id` in order to unassign any assigned user. The `SelectInput` however doesn't work with a `null` value for an option.

### Testing styled components

`jest-styled-components` is loaded by default now in `internals/testing/test-bundler.js`

### Restructuring files

I have restructured the following components I've touched, according to the rules described below them.

- [`List`](src/signals/incident-management/containers/IncidentOverviewPage/components/List/List.js)
- [`MetaList`](src/signals/incident-management/containers/IncidentDetail/components/MetaList/MetaList.js)
- [`ChangeValue`](src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/ChangeValue.js)

#### Component files

Lets say we have a Component called `List` with some styled components and unit test. We would then have the following files:

- `List/index.js` barrel file exporting the List component
- `List/List.js` component
- `List/List.styles.js` styled components
- `List/List.test.js` unit tests

This way each file name clearly indicates which component it belongs to and what it contains or does in case it's not the component itself.

#### Styling

Define styled components in a separate file named `<Component>.styles.js`.

Naming styled components is based on [this article](https://medium.com/inturn-eng/naming-styled-components-d7097950a245).

Import the styles into the component file with

```JavaScript
import * as S from './<Component>.styles';
```

Use the styled components in your component as

```JSX
<S.StyledComponent ...>
```

When you use a styled component as a root for your component, name it the same as the component.
So, for instance, you have a `List` component, this could look as follows

`List.js`

```JSX
import * as S from './List.styles';

const List = ({ items }) => {
  return (
    <S.List>
      {items.map(item => (
        <S.Li value={item.name} />
      ))}
    </S.List>
  );
};

export default List;
```

`List.styles.js`

```JavaScript
import styled from 'styled-components';

export const List = styled.ul`
  list-style: none;
`;

export const Li = styled.li`
  margin: 0;
`;
```

2020-10-12 12:23 UTC, aditudorache requested changes
General remarks:
- The PR is too large and can't be easily reviewed.
- The styling changes and naming conventions are out of scope here; please remove these changes and submit an ADR with the proposals first so we can discuss about it. Renaming the a file and then making changes in it makes the reivew difficult. Can we think about a solution (maybe in two steps) where first the files are renamed and then the changes re made? 
- `jest-styled-components` refactoring is out of scope; please submit a separate (Chore)PR.

2020-10-12 12:40 UTC, aditudorache reviewed
Can we wait with the refactoring of `jest-styled-components` until the enabling of typescript? I remember from another project there were some issues with inclusion of this package in the `test-bundle.ts`.

2020-10-12 13:25 UTC, boris-arkenaar commented
Thanks @aditudorache 
I was already afraid this might get a bit too big and complicated for one PR. You are right to suggest splitting thinks up and submitting a ADR for the file system changes.

2020-10-19 08:12 UTC, aditudorache requested changes

2020-10-19 08:13 UTC, aditudorache commented
Nice work on the unittests!

2020-10-19 08:54 UTC, boris-arkenaar commented on src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/index.test.js
> +describe('ChangeValue', () => {
I don't like these brackets in the name. It's not necessary, the name itself is clear enough.

2020-10-19 08:59 UTC, boris-arkenaar commented on src/signals/incident-management/containers/IncidentDetail/components/ChangeValue/index.js
> +  component = SelectInput,
That's how it was already. Not going to change now.

2020-10-19 09:03 UTC, boris-arkenaar commented on src/signals/incident-management/context.js
> +const initialContext = { districts: undefined, users: undefined };
Removed the `loading` since it's not being used anywhere.

2020-10-19 09:07 UTC, boris-arkenaar commented on src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js
> +const Td = styled.td`
The comment indicated it was done to make sure icon and text would not be wrapped. This is also achieved with the much simpler `white-space: nowrap`.
Setting explicit widths is very fragile and decreases maintainability and refactorability significantly!

2020-10-19 09:25 UTC, aditudorache commented on src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js
> +const Td = styled.td`
I'll contact the designer to make sure this was the intention.

2020-10-20 10:26 UTC, boris-arkenaar commented on src/signals/incident-management/containers/IncidentOverviewPage/components/List/index.js
> +const Td = styled.td`
Reverted this change for now. Opening a new PR with this change only, when this PR has been merged.

2020-10-20 11:00 UTC, aditudorache approved these changes

2020-10-20 11:00 UTC, merged