[SIG-3127] Read sources from the backend
Amsterdam/signals-frontend pull request #1224
Opened 2020-11-03 09:46 UTC by aditudorache

This PR
- Enables using the `source` data from the API
- Removes the  `fetchSourcesFromBackend` as is no longer necessary
- Fixes a bug by using the sources name instead of if in the filter requests

2020-11-03 16:09 UTC, MauritsR requested changes
Looks good (only a minor change necessary)

2020-11-03 16:09 UTC, MauritsR commented on src/signals/incident-management/__tests__/selectors.test.js
> +    it('should not work without sources', () => {
This test is a duplicate of the one on line 313 (can be removed)

2020-11-04 07:45 UTC, MauritsR approved these changes

2020-11-04 08:45 UTC, jpoppe approved these changes

2020-11-04 09:04 UTC, merged