Feature/89 map assets
Amsterdam/signals-frontend pull request #1266
Opened 2020-11-18 16:08 UTC by boris-arkenaar

closes #Signalen/frontend#89

Still contains changes from #1250. Will clear up when that PR has been merged.

**Changes**

This PR makes a generic version of the `MapSelect` component(s) and renames the old one(s) to `MapSelectAmsterdam`.

The following components

- `src/components/MapSelect`
- `src/signals/incident/components/IncidentPreview/components/MapSelect`
- `src/signals/incident/components/form/MapSelect`

have been copied to a `MapSelectAmsterdam` version in their respective locations. This means a whole lot of new files and lines of code in the diff, but you can skip over all of these since they haven't changed. So, don't let the big changeset scare you :)

All the `MapSelect` versions are now made generic and some functionality (like custom icons) has been dropped (for now). So, do check these changes out.

Added two open source icons and referenced the author in the readme.

2020-11-19 08:06 UTC, boris-arkenaar commented
Upped the jest thresholds, but for functions, I had to lower it a bit. This is because of the copy of the `MapSelect` component(s).

2020-11-23 12:00 UTC, aditudorache requested changes

2020-11-24 09:40 UTC, boris-arkenaar commented on src/components/MapSelect/index.js
> +    lnglatString => {
There are now two versions of bounding box strings though. A lat-lng version, and a lng-lat version.

2020-11-24 09:42 UTC, boris-arkenaar commented on src/components/MapSelect/index.js
> +              icon: selection.current.has(feature.properties[idField]) ? LeafletDotSelectedIcon : LeafletDotIcon,
Not necessary for this first iteration. No functionality is lost; the old functionality resides in `MapSelectAmsterdam`.

2020-11-24 09:44 UTC, boris-arkenaar commented on src/components/MapSelectAmsterdam/index.js
> +import React, { useLayoutEffect, useEffect, useState, useCallback, useMemo, useRef } from 'react';
No, there is no relation. This is simply the old version of `MapSelect` exactly as it was. When we iterate further we can have all functionality in the new `MapSelect` and `MapSelectAmsterdam` could go. Did you read the description of this PR? ;)

2020-11-24 09:45 UTC, boris-arkenaar commented on src/components/MapSelect/index.js
Yes. I  moved that up to the next iteration though.

2020-11-24 09:46 UTC, boris-arkenaar commented on src/components/MapSelect/index.js
> -  legend: PropTypes.arrayOf(
Yes. Next iteration ;)

2020-12-01 09:37 UTC, boris-arkenaar commented
See Signalen/frontend#92 for expanding `MapSelectGeneric`.

2020-12-02 08:26 UTC, aditudorache approved these changes
Looks good for now, further integration between the 2 MapSelect and MapSelectGeneric will follow!

2020-12-02 08:41 UTC, MauritsR approved these changes

2020-12-02 08:43 UTC, merged