[SIG-3484] Remove icon url on save
Amsterdam/signals-frontend pull request #1362
Opened 2021-01-21 14:09 UTC by aditudorache

This PR implements the configuration of the data that can be posted in the extra questions. The only accepted format is {id, type, description}. T

2021-01-22 09:34 UTC, MauritsR requested changes

2021-01-22 09:34 UTC, MauritsR commented on src/signals/incident/services/convert-value/index.ts
> +const convertValue = (value: unknown = undefined, postPropertyNames: string[] = []): any => {
The returnType of this function is also `unknown`

2021-01-22 09:34 UTC, MauritsR commented on src/signals/incident/services/convert-value/index.ts
> +const convertValue = (value: unknown = undefined, postPropertyNames: string[] = []): any => {
Not sure if defaulting to undefined is useful, since by definition a prop that is not passed is undefined

2021-01-22 09:34 UTC, MauritsR commented on src/signals/incident/services/convert-value/index.ts
> +  if (isArray(value) && postPropertyNames.length) {
Can this logic be implemented in a different utility function? It's not really _converting_ a value but it is filtering allowed properties

2021-01-22 09:34 UTC, MauritsR commented on src/signals/incident/services/convert-value/index.ts
> +  if (isArray(value) && postPropertyNames.length) {
Can't we use `Array.isArray`? That would also remove the need to cast to an array below

2021-01-22 09:34 UTC, MauritsR commented on src/signals/incident/services/convert-value/index.ts
> +  if (isArray(value) && postPropertyNames.length) {
It's preferred to use `unknown` instead of `any`

2021-01-22 09:34 UTC, MauritsR commented on src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts
> +      postPropertyNames: ['id', 'type', 'description'],
Something like `allowedPropertyNames` would me more descriptive (same below in the utility function).

2021-01-22 09:34 UTC, MauritsR commented on src/signals/incident/definitions/wizard-step-2-vulaan/afval.ts
> +      postPropertyNames: ['id', 'type', 'description'],
When should properties be added to the `additional-questions.md` docs?

2021-01-22 09:36 UTC, MauritsR commented
Is it not possible to add only the required data to the `addContainer` function and then (when icons need to be rendered) look up the icon url in the `meta` object when required?

2021-01-22 09:58 UTC, aditudorache commented
Great idea! I'll remove th iconUrl from the item and will lookup the icon in when it is used!

2021-01-25 09:05 UTC, aditudorache commented
Closed in favor of #1366

2021-01-25 09:05 UTC, closed without merging