[SIG-3623] Reset dynamic extra questions state
Amsterdam/signals-frontend pull request #1463
Opened 2021-03-15 17:02 UTC by MauritsR

### Changes

- Fixes state handling for extra questions that are dynamically added/removed

The visibility of some extra questions is dependent other questions. Previously, answers from questions that were dynamically removed (i.e. `isVisible` was set to `false`) were kept in the incident state. This caused these answers to still show up on the summary page.

2021-03-18 06:45 UTC, aditudorache requested changes
Not sure if out of scope, but would be nice to convert the IncidentForm component to a functional component.

2021-03-18 06:45 UTC, aditudorache commented on src/signals/incident/components/IncidentForm/index.test.js
> +    it('removes extra question data when the question is not visible anymore', () => {
Can we write the tests using the @testing-libraty?

2021-03-22 13:18 UTC, MauritsR commented
> Not sure if out of scope, but would be nice to convert the IncidentForm component to a functional component.

Out of scope for this story, but definitely something we should pick up!

2021-03-22 13:51 UTC, aditudorache approved these changes
Great job!

2021-03-22 14:47 UTC, merged