[SIG-3609] Radio focus
Amsterdam/signals-frontend pull request #1515
Opened 2021-04-07 13:36 UTC by aditudorache

This PR sets a custom focus on the radio because on Firefox the browser default focus is not visible on Mac

2021-04-08 11:28 UTC, MauritsR requested changes
Installing the new asc-ui fails. Can you synchronize with develop and try again? Might be that npm@7 is throwing a wrench into it.

2021-04-08 11:28 UTC, MauritsR commented on src/components/RadioButton/index.tsx
> +    <StyledRadio {...props} data-test="test" />
data-test?

2021-04-08 11:58 UTC, aditudorache commented on src/components/RadioButton/index.tsx
> +    <StyledRadio {...props} data-test="test" />
Good catch! Thanks!

2021-04-09 10:18 UTC, MauritsR commented
![Screenshot 2021-04-09 at 12 15 42](https://user-images.githubusercontent.com/10672773/114165896-57c46980-992d-11eb-89f8-dcc62f542968.png)
I get the result shown above, a mix of the native focus ring and a new black focus ring. Shouldn't the native ring be shown, just more visible? 

This document also describes using the default focus state: [design system - focus state](https://designsystem.amsterdam.nl/7awj1hc9f/p/17684a-focus-state)

2021-04-12 05:48 UTC, aditudorache commented
> ![Screenshot 2021-04-09 at 12 15 42](https://user-images.githubusercontent.com/10672773/114165896-57c46980-992d-11eb-89f8-dcc62f542968.png)
> I get the result shown above, a mix of the native focus ring and a new black focus ring. Shouldn't the native ring be shown, just more visible?
> 
> This document also describes using the default focus state: [design system - focus state](https://designsystem.amsterdam.nl/7awj1hc9f/p/17684a-focus-state)

It would be the best solution but I don't think is possible. The way how the native focus is shown is the browser responsibility. I couldn't find a way to do that in the application, do you have any suggestion?

2021-04-14 07:13 UTC, MauritsR approved these changes
Looks good, but can you install the packages using npm@7 and recommit the package-lock.json?

2021-04-14 08:03 UTC, merged