[SIG-4001] Error message component already in Dom to help screen readers
Amsterdam/signals-frontend pull request #1951
Opened 2021-12-24 15:33 UTC by kiruys

To do:
- create test
- extend this to other components

2022-01-12 07:05 UTC, janjaap requested changes

2022-01-12 07:05 UTC, janjaap commented on src/components/ErrorMessage/ErrorMessage.tsx
> +    `}
This change won't solve the issue at hand; the point is that the element that holds the error message, should be present in the DOM. Setting its `display` value to 'none' will effectively hide it for browsers and screen readers which defeats the purpose.
See https://www.w3.org/WAI/WCAG21/working-examples/aria-role-status-searchresults/ for an example.

2022-01-17 12:54 UTC, kiruys commented on src/components/FileInput/FileInput.tsx
> +        invalid={errorMessages.length > 0}
invalid props is removed

2022-01-18 08:57 UTC, janjaap requested changes

2022-01-18 08:57 UTC, janjaap commented on src/signals/incident/components/form/FormField/FormField.tsx
> +          />
These only need to be rendered when there is an actual error to display.

2022-01-18 08:57 UTC, janjaap commented on src/components/TextArea/TextArea.tsx
>            />
This component should only be rendered when there is an actual error message that needs to be shown.

2022-01-21 08:24 UTC, closed without merging

2022-01-21 08:24 UTC, kiruys commented
Created new PR to fix this