[SIG 4555] difference bedankt pages.
Amsterdam/signals-frontend pull request #2153
Opened 2022-05-11 12:50 UTC by OscarBakker

## Signalen

Before opening a pull request, please ensure:
https://datapunt.atlassian.net/browse/SIG-4555?atlOrigin=eyJpIjoiZDg5OTA5MWZmNDlhNGY3Mjg5YmEwNThjOWE4NGY1ZjEiLCJwIjoiaiJ9
- [ ] Double-check your branch is based on `develop` and targets `develop`
- [ ] Pull request has tests (we are going for 100% coverage!)
- [ ] Code is well-commented, linted and follows project conventions
- [ ] Committed source code is headed by the correct SPDX license expression

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

2022-05-11 13:25 UTC, OscarBakker commented on src/signals/incident/containers/KtoContainer/index.js
> -      const { detail } = errorCheck
try catch not needed!

2022-05-12 07:12 UTC, kiruys commented on src/signals/incident/containers/KtoContainer/index.js
> -      const { detail } = errorCheck
👍

2022-05-12 07:15 UTC, kiruys approved these changes
Looks good! One minor thing, can you do something about the warning in Selector.test.tsx? I have fixed the other one.

2022-05-12 07:48 UTC, kiruys requested changes
checkte de branch nog even uit en toen zag ik toch nog een paar dingetjes:

- in het ja formulier staat nog de vraag of er contact opgenomen mag worden. 
- de balk onder de header klopt ook niet helemaal (de balk is te smal).

2022-05-12 13:01 UTC, kiruys commented
And the name of the feature flag is `REPORTER_MAIL_HANDLED_NEGATIVE_CONTACT_ENABLED`

2022-05-18 11:24 UTC, OscarBakker commented
> And the name of the feature flag is `REPORTER_MAIL_HANDLED_NEGATIVE_CONTACT_ENABLED`

- [ ] toevoegen en testen

2022-05-19 07:41 UTC, kiruys approved these changes

2022-05-23 08:48 UTC, merged