[feat-4944]: Get paginated results in IncidentMap.tsx.
Amsterdam/signals-frontend pull request #2455
Opened 2023-01-10 12:11 UTC by OscarBakker

Ticket: [SIG-1234](https://datapunt.atlassian.net/browse/SIG-1234)

## Signalen

##todo
- [ ] abort request when a new one is made
- [ ] debounce the call, moving the map can result in request spam
- [ ] write tests
- [ ] use x-total-count when cors_expose_header is set in the backend

Before opening a pull request, please ensure:

- Make sure your PR title follows naming conventions: [feat-1234]: name feature
- Double-check your branch is based on `main` and targets `main`
- Pull request has tests (we are going for 100% coverage!)
- Code is well-commented, linted and follows project conventions
- Committed source code is headed by the correct SPDX license expression

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

2023-01-16 14:32 UTC, SireeKoolenWijkstra requested changes
Hi Oscar,
Ik heb je code uitgecheckt en daarna local geprobeerd te draaien. Ik krijg een melding pagina niet gevonden als ik naar de meldingenkaart ga. 
![image](https://user-images.githubusercontent.com/25867841/212702187-5aed4d39-2b58-49a7-9c26-878ebfafbb71.png)

2023-01-16 15:12 UTC, SireeKoolenWijkstra commented on src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx
> +    throttle((arg) => getIncidents(arg), 500),
- Waarom gekozen voor 500 miliseconden? Zat daar een filosofie achter? 
- Waarom geen leading en trailing options? Het lijkt alsof je daarmee kan cancellen. Wat an sich top klinkt?

2023-01-16 15:17 UTC, SireeKoolenWijkstra approved these changes
Vond het moeilijk te checken, maar lgtm. Heb nog een tweetal vragen voor mijn eigen kennis.

2023-01-16 16:11 UTC, OscarBakker commented on src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx
> +    throttle((arg) => getIncidents(arg), 500),
- minder kan ook, maar ik had het 1 en ander geprobeerd en hierbij vond ik m mooi reageren
- met leading en trailing (die default aanstaan) kun je niet cancellen. Je kunt wel het aantal calls beperken
- als de call wordt gemaakt en binnen de 500 seconden een tweede call gedaan wordt en de server heeft nog niet geantwoord (nog steeds traveling), dan kun je die eerste call aborten met de abort controller.

2023-01-17 12:24 UTC, vdegraaf approved these changes
Nice! Does seem to work great. 
I think however a we could have reused the useFetch setup and just fetch new data as long as the backend sends an extra request link and then return the incidents when all succeeded. 

Anyhow, approved with three small comments!

2023-01-17 12:24 UTC, vdegraaf commented on src/signals/IncidentMap/components/IncidentMap/usePaginatedIncidents.ts
> +// Copyright (C) 2023 Gemeente Amsterdam
2022 - 2023

2023-01-17 12:24 UTC, vdegraaf commented on src/signals/IncidentMap/components/IncidentMap/usePaginatedIncidents.ts
> +    Feature<PointLatLng, Properties>[]
This is the type `Incident` in `src/signals/IncidentMap/types/incident-map.ts`

2023-01-17 14:19 UTC, merged