[fix-5003]: kto header
Amsterdam/signals-frontend pull request #2489
Opened 2023-02-07 10:35 UTC by vdegraaf

Ticket: [SIG-5003](https://gemeente-amsterdam.atlassian.net/browse/SIG-5003)

Add a topic to "Over iets anders" answer in the negative feedback kto form. 

Currently vs. New
<img width="1666" alt="Screenshot 2023-02-07 at 11 34 42" src="https://user-images.githubusercontent.com/46756331/217221450-8cc5644b-d637-4d2c-9b9d-cfff8f450e1b.png">

2023-02-07 12:57 UTC, OscarBakker approved these changes
goodgood

2023-02-07 13:05 UTC, SireeKoolenWijkstra requested changes
You also changed it for KTO positive. I don't think that's what should happen.

2023-02-07 13:12 UTC, SireeKoolenWijkstra commented on src/signals/incident/containers/KtoContainer/index.test.js
> +
This doesn't exclude it from happening in the KTO positive flow.

2023-02-07 19:58 UTC, vdegraaf commented
@SireeKoolenWijkstra the change is good for both positive and negative kto form. There was an issue with a double header in the positive flow, but that has been fixed by Jelle now. Check: 
<img width="1702" alt="Screenshot 2023-02-07 at 20 58 29" src="https://user-images.githubusercontent.com/46756331/217351916-9b726729-a328-40df-8c63-721d133b6e69.png">

2023-02-08 08:02 UTC, SireeKoolenWijkstra approved these changes
Looks good to me

2023-02-08 08:24 UTC, merged