[feat-5459]: Put search bar to top menu
Amsterdam/signals-frontend pull request #2755
Opened 2023-11-14 15:27 UTC by vdegraaf

Ticket: [SIG-5459](https://gemeente-amsterdam.atlassian.net/browse/SIG-5459)

## Signalen

Before opening a pull request, please ensure:

- Make sure your PR title follows naming conventions: [feat-1234]: name feature
- Double-check your branch is based on `main` and targets `main`
- Pull request has tests (we are going for 100% coverage!)
- Code is well-commented, linted and follows project conventions
- Committed source code is headed by the correct SPDX license expression

Be kind to code reviewers, please try to keep pull requests as small and focused as possible :)

2023-11-15 09:18 UTC, OscarBakker requested changes

2023-11-15 12:11 UTC, vdegraaf commented on src/signals/IncidentMap/components/IncidentMap/styled.ts
> +        top: 124px;
it's not used. Removed it.

2023-11-15 16:15 UTC, OscarBakker approved these changes

2023-11-15 21:23 UTC, SireeKoolenWijkstra requested changes
- [ ] When I look up an address then the styling of the search bar changes. The border is only half there. 
![image](https://github.com/Amsterdam/signals-frontend/assets/25867841/964175e3-593a-45d9-9cb9-8cfdd5403346)

2023-11-15 21:23 UTC, SireeKoolenWijkstra commented on src/signals/IncidentMap/components/IncidentMap/IncidentMap.tsx
> +  const [mapMessage, setMapMessage] = useState<JSX.Element | string>('wrvsfdg')
I don't think this should be here.

2023-11-15 21:27 UTC, SireeKoolenWijkstra requested changes

2023-11-15 21:27 UTC, SireeKoolenWijkstra commented on src/signals/IncidentMap/components/AddressLocation/AddressSearchMobile.tsx
> +  onFocus: any
Shouldn't this be a function?

2023-11-16 11:51 UTC, SireeKoolenWijkstra approved these changes
lgtm

2023-11-16 11:51 UTC, merged